### ISSUE TITLE
Gute Idee aber ...

### ISSUE THREAD

**Issue by 0scarZulu** [jason0611/FS22_CultivatorSettings#3]
Hey :) 

danke für deine Erweiterung. Wäre es aber nicht realistischer in der Umsetzung wenn du das nicht im Shop machst sondern on the fly auf der Machine bzw. auf dem Feld die Tiefe ändert per Taste oder DBL? Also ähnlich wie beim Corona von Vertex? Oder geht das nicht weil es dann wieder zu nah an ihrem Script wäre wenn man das umsetzen würde? 

Cheers und Peace
Oz

**Comment by dashibo** [comment]
Ola, aber dafür hast du doch die Option "Isobus" in der Shopauswahl...

**Comment by jason0611** [comment]
Allerdings, das ist über die ISOBUS-Konfiguration umschaltbar. Standardbelegung dafür ist dann Strg+Alt+G.
