### ISSUE TITLE
Dashboard Live

### ISSUE THREAD

**Issue by MX5Marc** [jason0611/FS22_CultivatorSettings#4]
I love the idea of the extra immersion and role play this mod offers and will certainly be something that I use in my saves.

It feels like it'd be a great candidate for Dashboard Live. Is it compatible as way of seeing the cultivator setting in a screen or control box?

**Comment by jason0611** [comment]
Yes, DashboardLive already supports FS22_CultivatorSettings. :-)

**Comment by MX5Marc** [comment]
Amazing! :) Is it recognised directly via the Isobus, or are there any instructions to set it up?

**Comment by jason0611** [comment]
Just take a look into the dblCommand reference: https://github.com/jason0611/FS22_DashboardLive/releases/tag/1.4.0.0
In this version DBL can only recognize if a cultivator is set to normal mode or deep mode. After the next update, it will recognize the shallow mode, too.

**Comment by MX5Marc** [comment]
Many thanks :) I'll take a look and try and add it to my screens
